### ISSUE TITLE
Unsupported type class java.lang.String

### ISSUE THREAD

**Issue by minhtran-q** [bardackx/tiebreaker#2]
This app doesn't seem to support String type. String type is a common type, so I think this library should support String type.

`Exception in thread "main" java.lang.RuntimeException: Unsupported type class java.lang.String
	at com.bardackx.tiebreaker.MultiTypeComparator.lambda$new$16(MultiTypeComparator.java:69)
	at com.bardackx.tiebreaker.Tiebreaker.lambda$sort$4(Tiebreaker.java:75)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.bardackx.tiebreaker.Tiebreaker.sort(Tiebreaker.java:80)
	at com.bardackx.tiebreaker.Tiebreaker.sort(Tiebreaker.java:102)
	at com.bardackx.tiebreaker.Test.main(Test.java:27)
`

This little library is very useful to me, so can I contribute to this library?

**Comment by bardackx** [comment]
I forgot about this project, of course you can contribute

Do you have a test example of how do you want to use strings?

**Comment by minhtran-q** [comment]
My project uses a dynamic sort mechanism and sometimes needs to sort a string value. And your library fits that feature well. But it lacks String comparator.

**Comment by bardackx** [comment]
I just updated it to take advantage of objects implementing the comparable interface, so strings are now supported too

**Comment by minhtran-q** [comment]
Oh, thank for your update.
